mkdir build && cd build
#cmake -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_EXAMPLES=ON ..
cmake -D CMAKE_BUILD_TYPE=DEBUG -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_CXX_STANDARD=14 -DWITH_CUDA=OFF -DBUILD_EXAMPLES=ON ..
make -j12
